import StudyShell from "@/components/StudyShell";
import SessionCard, { type SessionCardData } from "@/components/SessionCard";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowRight, CalendarDays, PlusCircle, Sparkles, UsersRound } from "lucide-react";
import { Link } from "wouter";

function CardSkeleton() { return <div className="h-64 animate-pulse rounded-2xl bg-white" />; }

export default function Dashboard() {
  const { user } = useAuth();
  const { data, isLoading, error } = trpc.dashboard.get.useQuery();
  const firstName = user?.name?.split(" ")[0] || "Scholar";
  return <StudyShell>
    <div className="mx-auto max-w-6xl">
      <section className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#0d7676]">Your study rhythm</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight text-[#16314d]">Good to see you, {firstName}.</h1><p className="mt-3 max-w-xl text-[#607487]">Keep your next commitments visible, or make space for a new session.</p></div><Link href="/sessions/new" className="inline-flex h-11 items-center justify-center rounded-xl bg-[#0d7676] px-4 text-sm font-bold text-white shadow-sm transition hover:bg-[#095e61]"><PlusCircle className="mr-2 size-4" />Host a session</Link></section>
      <section className="mt-9 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[#16314d] p-5 text-white"><CalendarDays className="size-5 text-[#e7bd5c]" /><p className="mt-7 text-3xl font-semibold">{data?.joined.length ?? "—"}</p><p className="mt-1 text-sm text-[#c7e0dc]">Upcoming commitments</p></div><div className="rounded-2xl bg-[#dff2ed] p-5"><UsersRound className="size-5 text-[#0d7676]" /><p className="mt-7 text-3xl font-semibold text-[#16314d]">{data?.hosted.length ?? "—"}</p><p className="mt-1 text-sm text-[#527278]">Sessions you host</p></div><div className="rounded-2xl bg-[#f8efd8] p-5"><Sparkles className="size-5 text-[#a2761f]" /><p className="mt-7 text-3xl font-semibold text-[#16314d]">{data?.upcoming.length ?? "—"}</p><p className="mt-1 text-sm text-[#786f58]">Open to discover</p></div></section>
      {error && <div className="mt-8 rounded-xl border border-[#f0caca] bg-[#fff4f4] p-4 text-sm text-[#9b4141]">We could not load your study overview. Please refresh and try again.</div>}
      <section className="mt-11"><div className="flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#0d7676]">Next up</p><h2 className="mt-2 font-serif text-3xl font-semibold">Your upcoming sessions</h2></div><Link href="/my-sessions" className="hidden items-center gap-1 text-sm font-bold text-[#0d7676] hover:underline sm:inline-flex">View all <ArrowRight className="size-4" /></Link></div>
        <div className="mt-5 grid gap-5 md:grid-cols-2">{isLoading ? <><CardSkeleton /><CardSkeleton /></> : data?.joined.length ? data.joined.map((session) => <SessionCard key={session.id} session={session as SessionCardData} />) : <div className="rounded-2xl border border-dashed border-[#b7d8d1] bg-white p-8 md:col-span-2"><h3 className="text-lg font-bold">Nothing on your calendar yet.</h3><p className="mt-2 max-w-lg text-sm leading-6 text-[#607487]">Explore study sessions by topic, time, format, or location. When you find a good fit, you can join directly from the session details.</p><Link href="/discover" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#0d7676] hover:underline">Discover sessions <ArrowRight className="size-4" /></Link></div>}</div>
      </section>
      <section className="mt-11"><div className="flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#a2761f]">Host activity</p><h2 className="mt-2 font-serif text-3xl font-semibold">Sessions you are leading</h2></div><Link href="/sessions/new" className="hidden text-sm font-bold text-[#0d7676] hover:underline sm:block">Create another</Link></div>
        <div className="mt-5 grid gap-5 md:grid-cols-2">{isLoading ? <><CardSkeleton /><CardSkeleton /></> : data?.hosted.length ? data.hosted.map((session) => <SessionCard key={session.id} session={{ ...session, location: null, onlineLink: null, format: "in_person", hostName: null } as SessionCardData} />) : <div className="rounded-2xl border border-[#d7e8e4] bg-white p-7 md:col-span-2"><p className="font-bold">Ready to gather a focused group?</p><p className="mt-2 text-sm text-[#607487]">Host a session with a clear objective and limited capacity, so peers know exactly what they are committing to.</p><Link href="/sessions/new" className="mt-4 inline-flex text-sm font-bold text-[#0d7676] hover:underline">Create a session →</Link></div>}</div>
      </section>
      <section className="mt-11 rounded-2xl border border-[#d7e8e4] bg-white p-6"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#0d7676]">Recent activity</p><h2 className="mt-2 font-serif text-3xl font-semibold">Session updates</h2><div className="mt-5 divide-y divide-[#e5efec]">{isLoading ? <div className="h-24 animate-pulse rounded-xl bg-[#f1f7f5]" /> : data?.activity.length ? data.activity.map((item) => <div key={item.id} className="flex items-start gap-3 py-4"><span className="mt-1.5 size-2 rounded-full bg-[#e7bd5c]" /><div><p className="font-semibold text-[#16314d]">{item.message}</p><p className="mt-1 text-xs text-[#78909e]">{item.sessionTitle || "StudySync"} · {new Date(item.createdAt).toLocaleDateString()}</p></div></div>) : <p className="py-4 text-sm leading-6 text-[#607487]">Your session confirmations, waitlist updates, and hosting changes will appear here.</p>}</div></section>
    </div>
  </StudyShell>;
}
