import StudyShell from "@/components/StudyShell";
import SessionCard, { type SessionCardData } from "@/components/SessionCard";
import { trpc } from "@/lib/trpc";
import { CalendarDays, PlusCircle } from "lucide-react";
import { Link } from "wouter";

export default function MySessions() {
  const { data, isLoading, error } = trpc.dashboard.get.useQuery();
  return <StudyShell><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#0d7676]">Commitments and hosting</p><h1 className="mt-2 font-serif text-4xl font-semibold">My sessions</h1><p className="mt-3 text-[#607487]">Keep the groups you join and lead in one calm workspace.</p></div><Link href="/sessions/new" className="inline-flex h-11 items-center justify-center rounded-xl bg-[#0d7676] px-4 text-sm font-bold text-white hover:bg-[#095e61]"><PlusCircle className="mr-2 size-4" />Host a session</Link></div>{error && <div className="mt-6 rounded-xl border border-[#f0caca] bg-[#fff4f4] p-4 text-sm text-[#9b4141]">Your sessions could not be loaded. Please retry.</div>}
    <section className="mt-10"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#e5f4f0] text-[#0d7676]"><CalendarDays className="size-5" /></span><div><h2 className="font-serif text-3xl font-semibold">Joined sessions</h2><p className="text-sm text-[#607487]">Your upcoming learning commitments.</p></div></div><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{isLoading ? <div className="h-60 animate-pulse rounded-2xl bg-white md:col-span-2" /> : data?.joined.length ? data.joined.map((session) => <SessionCard key={session.id} session={session as SessionCardData} />) : <div className="rounded-2xl border border-dashed border-[#b7d8d1] bg-white p-8 md:col-span-2 xl:col-span-3"><p className="font-bold">You have not joined any upcoming sessions.</p><Link href="/discover" className="mt-3 inline-flex text-sm font-bold text-[#0d7676] hover:underline">Find a session →</Link></div>}</div></section>
    <section className="mt-12"><div><h2 className="font-serif text-3xl font-semibold">Hosted sessions</h2><p className="mt-1 text-sm text-[#607487]">Sessions where you are responsible for the plan and participants.</p></div><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{isLoading ? <div className="h-60 animate-pulse rounded-2xl bg-white md:col-span-2" /> : data?.hosted.length ? data.hosted.map((session) => <SessionCard key={session.id} session={{ ...session, location: null, onlineLink: null, format: "in_person", hostName: null } as SessionCardData} />) : <div className="rounded-2xl border border-dashed border-[#b7d8d1] bg-white p-8 md:col-span-2 xl:col-span-3"><p className="font-bold">You are not hosting an upcoming session.</p><Link href="/sessions/new" className="mt-3 inline-flex text-sm font-bold text-[#0d7676] hover:underline">Host a focused group →</Link></div>}</div></section>
  </div></StudyShell>;
}
