import StudyShell from "@/components/StudyShell";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Check, GraduationCap, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function Profile() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const profile = trpc.profile.get.useQuery();
  const [form, setForm] = useState({ displayName: "", bio: "", timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", studyInterests: "" });
  useEffect(() => { if (profile.data) setForm({ displayName: profile.data.displayName || profile.data.name || user?.name || "", bio: profile.data.bio || "", timezone: profile.data.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", studyInterests: profile.data.studyInterests || "" }); }, [profile.data, user?.name]);
  const update = trpc.profile.update.useMutation({ onSuccess: () => { toast.success("Your profile is updated."); utils.profile.get.invalidate(); }, onError: (error) => toast.error(error.message) });
  const initial = (form.displayName || user?.name || "S").trim().charAt(0).toUpperCase();
  return <StudyShell><div className="mx-auto max-w-4xl"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#0d7676]">Personal study space</p><h1 className="mt-2 font-serif text-4xl font-semibold">Your profile</h1><p className="mt-3 text-[#607487]">Give study partners the context they need, without sharing more than you choose.</p></div>
    <section className="mt-8 grid gap-6 lg:grid-cols-[280px_minmax(0,1fr)]"><aside className="rounded-[1.75rem] bg-[#16314d] p-7 text-white"><span className="grid size-16 place-items-center rounded-full bg-[#c9ece4] text-2xl font-bold text-[#0d7676]">{initial}</span><h2 className="mt-6 font-serif text-2xl font-semibold">{form.displayName || "Your name"}</h2><p className="mt-2 text-sm text-[#c8e1dc]">{user?.email || "Signed-in StudySync member"}</p><div className="mt-7 border-t border-white/15 pt-5 text-sm text-[#c8e1dc]"><p className="flex items-center gap-2"><GraduationCap className="size-4 text-[#e7bd5c]" />Participant and host</p><p className="mt-3 flex items-center gap-2"><Check className="size-4 text-[#e7bd5c]" />Profile is yours to control</p></div></aside>
      <form onSubmit={(event) => { event.preventDefault(); update.mutate(form); }} className="rounded-2xl border border-[#d7e8e4] bg-white p-6 shadow-[0_20px_48px_-40px_rgba(19,50,77,0.55)] sm:p-8">{profile.error && <div className="mb-5 rounded-xl bg-[#fff4f4] p-3 text-sm text-[#9b4141]">We could not load your current details. You can still update your profile.</div>}<div className="grid gap-6"><label><span className="field-label">Display name</span><input required minLength={2} value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} className="field-input" placeholder="How should study partners know you?" /></label><label><span className="field-label">Short study bio</span><textarea value={form.bio} onChange={(event) => setForm({ ...form, bio: event.target.value })} className="field-input min-h-28 resize-y" placeholder="Share your study goals, strengths, or preferences." /></label><label><span className="field-label">Study interests</span><input value={form.studyInterests} onChange={(event) => setForm({ ...form, studyInterests: event.target.value })} className="field-input" placeholder="e.g. data structures, statistics, language practice" /></label><label><span className="field-label">Timezone</span><input required value={form.timezone} onChange={(event) => setForm({ ...form, timezone: event.target.value })} className="field-input" placeholder="e.g. America/New_York" /></label></div><div className="mt-8 flex justify-end border-t border-[#e5efec] pt-6"><button disabled={update.isPending} className="inline-flex h-11 items-center justify-center rounded-xl bg-[#0d7676] px-4 text-sm font-bold text-white hover:bg-[#095e61] disabled:opacity-60"><Save className="mr-2 size-4" />{update.isPending ? "Saving…" : "Save profile"}</button></div></form>
    </section>
  </div></StudyShell>;
}
