import StudyShell from "@/components/StudyShell";
import { formatSessionTime } from "@/components/SessionCard";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, Edit3, ExternalLink, MapPin, Monitor, Trash2, UserRound, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Link, useLocation, useRoute } from "wouter";

export default function SessionDetail() {
  const [, params] = useRoute("/sessions/:id"); const id = Number(params?.id);
  const [, setLocation] = useLocation(); const { user } = useAuth(); const utils = trpc.useUtils();
  const { data, isLoading, error } = trpc.sessions.detail.useQuery({ id });
  const enroll = trpc.sessions.enroll.useMutation({ onSuccess: (result) => { toast.success(result.status === "joined" ? "You are confirmed for this session." : `This session is full—you are number ${result.position} on the waitlist.`); utils.sessions.detail.invalidate({ id }); utils.dashboard.get.invalidate(); }, onError: (err) => toast.error(err.message) });
  const leave = trpc.sessions.leave.useMutation({ onSuccess: () => { toast.success("Your session commitment was removed."); utils.sessions.detail.invalidate({ id }); utils.dashboard.get.invalidate(); }, onError: (err) => toast.error(err.message) });
  const cancel = trpc.sessions.cancel.useMutation({ onSuccess: () => { toast.success("The session has been cancelled."); setLocation("/my-sessions"); }, onError: (err) => toast.error(err.message) });
  if (isLoading) return <StudyShell><div className="mx-auto h-96 max-w-5xl animate-pulse rounded-3xl bg-white" /></StudyShell>;
  if (error || !data) return <StudyShell><div className="mx-auto max-w-3xl rounded-2xl border border-[#f0caca] bg-white p-10 text-center"><h1 className="font-serif text-3xl font-semibold">This session is unavailable.</h1><p className="mt-3 text-[#607487]">It may have been removed, or you may not have permission to view it.</p><Link href="/discover" className="mt-6 inline-flex text-sm font-bold text-[#0d7676] hover:underline">Return to discovery →</Link></div></StudyShell>;
  const isHost = data.hostId === user?.id; const openSeats = Math.max(data.capacity - data.seatsTaken, 0); const pending = enroll.isPending || leave.isPending || cancel.isPending;
  return <StudyShell><div className="mx-auto max-w-5xl"><Link href="/discover" className="inline-flex items-center gap-2 text-sm font-bold text-[#0d7676] hover:underline"><ArrowLeft className="size-4" />Back to discovery</Link>
    <section className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_330px]"><article className="rounded-[1.75rem] bg-[#16314d] p-7 text-white sm:p-9"><div className="flex flex-wrap items-center gap-2">{data.tags.map((tag) => <span key={tag} className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.1em] text-[#bde5dc]">{tag}</span>)}<span className="rounded-full bg-[#e7bd5c] px-3 py-1 text-xs font-bold text-[#16314d]">{data.subject}</span></div><h1 className="mt-6 font-serif text-4xl font-semibold leading-tight">{data.title}</h1><p className="mt-5 max-w-2xl whitespace-pre-line leading-7 text-[#c9e1dc]">{data.description}</p><div className="mt-8 grid gap-3 border-t border-white/15 pt-6 sm:grid-cols-2"><p className="flex items-center gap-2 text-sm text-[#d5e8e4]"><CalendarDays className="size-4 text-[#e7bd5c]" />{formatSessionTime(data.startsAt)}</p><p className="flex items-center gap-2 text-sm text-[#d5e8e4]"><Clock3 className="size-4 text-[#e7bd5c]" />Ends {new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit" }).format(new Date(data.endsAt))}</p><p className="flex items-center gap-2 text-sm text-[#d5e8e4]"><span>{data.format === "online" ? <Monitor className="size-4 text-[#e7bd5c]" /> : <MapPin className="size-4 text-[#e7bd5c]" />}</span>{data.format === "online" ? "Online study room" : data.location || "Location to follow"}</p>{data.onlineLink && <a href={data.onlineLink} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-sm font-bold text-[#e7bd5c] hover:underline"><ExternalLink className="size-4" />Open meeting link</a>}</div></article>
      <aside className="rounded-[1.75rem] border border-[#d7e8e4] bg-white p-6 shadow-[0_22px_55px_-42px_rgba(19,50,77,0.5)]"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#0d7676]">Attendance</p><p className="mt-3 font-serif text-4xl font-semibold text-[#16314d]">{openSeats}<span className="ml-2 text-base font-sans font-medium text-[#607487]">seats open</span></p><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#e5efec]"><div className="h-full rounded-full bg-[#0d7676]" style={{ width: `${Math.min(100, data.seatsTaken / data.capacity * 100)}%` }} /></div><p className="mt-3 flex items-center gap-2 text-sm text-[#607487]"><UsersRound className="size-4 text-[#0d7676]" />{data.seatsTaken} of {data.capacity} participants confirmed</p><div className="mt-7 border-t border-[#e5efec] pt-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#78909e]">Hosted by</p><div className="mt-3 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#dff2ed] text-[#0d7676]"><UserRound className="size-5" /></span><div><p className="font-bold">{data.hostName || "StudySync host"}</p><p className="line-clamp-2 text-xs leading-5 text-[#607487]">{data.hostBio || "Committed to a focused, welcoming study space."}</p></div></div></div>
        <div className="mt-7">{isHost ? <div className="space-y-3"><Link href={`/sessions/${id}/edit`} className="flex h-11 items-center justify-center rounded-xl bg-[#0d7676] text-sm font-bold text-white hover:bg-[#095e61]"><Edit3 className="mr-2 size-4" />Edit session</Link><button disabled={pending} onClick={() => { if (window.confirm("Cancel this study session? Participants will no longer be able to join.")) cancel.mutate({ id }); }} className="flex h-11 w-full items-center justify-center rounded-xl border border-[#e8caca] text-sm font-bold text-[#a04444] hover:bg-[#fff5f5] disabled:opacity-60"><Trash2 className="mr-2 size-4" />Cancel session</button></div> : data.userState === "joined" ? <button disabled={pending} onClick={() => leave.mutate({ id })} className="flex h-11 w-full items-center justify-center rounded-xl border border-[#bddbd5] text-sm font-bold text-[#0d7676] hover:bg-[#eaf5f2] disabled:opacity-60">{pending ? "Updating…" : "Cancel attendance"}</button> : data.userState === "waitlisted" ? <div className="space-y-3 rounded-xl bg-[#fff6df] p-4 text-sm text-[#825b12]"><div><p className="font-bold">You are on the waitlist.</p><p className="mt-1">Your current position is #{data.waitlistPosition}.</p></div><button disabled={pending} onClick={() => leave.mutate({ id })} className="text-xs font-bold text-[#825b12] hover:underline">Leave waitlist</button></div> : <button disabled={pending || data.status !== "published"} onClick={() => enroll.mutate({ id })} className="flex h-11 w-full items-center justify-center rounded-xl bg-[#0d7676] text-sm font-bold text-white hover:bg-[#095e61] disabled:opacity-60"><CheckCircle2 className="mr-2 size-4" />{openSeats ? "Join this session" : "Join waitlist"}</button>}</div></aside>
    </section>
    {isHost && <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-[#d7e8e4] bg-white p-6"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#0d7676]">Host view</p><h2 className="mt-2 font-serif text-2xl font-semibold">Participant states</h2><div className="mt-5 divide-y divide-[#e5efec]">{data.participants.length ? data.participants.map((person) => <div key={person.id} className="flex items-center justify-between py-3"><div><p className="font-bold">{person.name || "Participant"}</p><p className="text-xs text-[#78909e]">Joined {new Date(person.joinedAt).toLocaleDateString()}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${person.status === "active" ? "bg-[#e5f4f0] text-[#0d7676]" : "bg-[#f5e9e9] text-[#a04444]"}`}>{person.status}</span></div>) : <p className="py-4 text-sm text-[#607487]">No participant records yet.</p>}</div></div><div className="rounded-2xl border border-[#d7e8e4] bg-white p-6"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#a2761f]">Capacity fallback</p><h2 className="mt-2 font-serif text-2xl font-semibold">Waitlist states</h2><div className="mt-5 divide-y divide-[#e5efec]">{data.waitlist.length ? data.waitlist.map((person) => <div key={person.id} className="flex items-center justify-between py-3"><div><p className="font-bold">#{person.position} · {person.name || "Participant"}</p><p className="text-xs text-[#78909e]">Added {new Date(person.createdAt).toLocaleDateString()}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${person.status === "waiting" ? "bg-[#fff6df] text-[#825b12]" : person.status === "promoted" ? "bg-[#e5f4f0] text-[#0d7676]" : "bg-[#f5e9e9] text-[#a04444]"}`}>{person.status}</span></div>) : <p className="py-4 text-sm text-[#607487]">The waitlist is clear.</p>}</div></div></section>}
  </div></StudyShell>;
}
